### ISSUE TITLE
Multiple <visibility> or <validity> elements support

### ISSUE THREAD

**Issue by Cirn09** [end2endzone/ShellAnything#53]
I have a idea about how to realize the logic of visibility judgment through xml.
Multiple visibility elements can be written at the same level, the attributes under the same element is the relationship of logical AND, and the relationship between different elements is the logical OR,

E.g:
```xml
<visibility start_time="08:00" end_time="10:00"/>
<visibility start_time="14:00" end_time="16:00"/>
```
it mean visible when `08:00<current_time<10:00 or 14:00<current_time<16:00`

**Comment by end2endzone** [comment]
As previously discussed in #50.

@Cirn09 Please note that `start_time` and `end_time` attributes of `<visibility>` elements are not currently supported by ShellAnything. Supporting new xml attributes through plugins is discussed in issue #50.

This issue is about supporting multiple `<visibility>` and `<validity>` elements in a single menu.
For example:
```xml
  <visibility maxfiles="1" maxfolders="0" fileextensions="txt;md;log;tex" />
  <visibility properties="allow_any_files" />
```
which means the menu will be visible if:

( maximum of 1 file selected **_and_**
&ensp; maximum of 0 folder selected **_and_**
&ensp; file's extensions is one of `txt;md;log;tex` )
  **_or_**
 ( property `allow_any_file_extensions` is not empty )

**Comment by end2endzone** [comment]
I see that you did not create a fork of ShellAnything. Would you like to contribute to the project? If so, please so in the comments and I will assign you this issue.

**Comment by Cirn09** [comment]
I have no experience in large C++ projects, dont know how to contribute this project, so I’m not going to create a fork.

**Comment by end2endzone** [comment]
@Cirn09 Hi. I have reintegrated the development branch into master. This is the first step towards plugins support. Would you like to review the feature and documentation before I close the issue? You can download a beta from https://ci.appveyor.com/project/end2endzone/shellanything/builds/36452958/job/0msbe2q39j0log8s/artifacts.
