### ISSUE TITLE
Menu name maximum length limit and escape string

### ISSUE THREAD

**Issue by Cirn09** [end2endzone/ShellAnything#55]
Menu name containing variables may have a large length, like `<menu name="${env.Path}">`.
Need to add a maximum length attribute to the menu element, like this:
```xml
<menu name="${env.Path}" max_length="16">
```

I tried some way, and couldn't display the string like "${env.Path}" in the Explorer menu, maybe the source code did not add support for escaping

**Comment by end2endzone** [comment]
You are right, I did not protect menus for a maximum length. I have also never tried something like this! That is a good idea. Having a too long string may even get the system (or at least, File Explorer) unstable.

I also did implement character escaping. I am not certain I need to. You should be able to set menus with values like `quote` or `double-quotes`. However, characters like `backslash` (ASCII code 08) may create strange behaviors. Will need to investigate furthur. Did you had something specific in mind?

P.S. If you need to display the content of ${env.Path} for debugging, then the following would be a better method:
```xml
<message caption="Content of env.path" title="${env.Path}" />
```
note also that content of the variable will also be written to the logs.

**Comment by end2endzone** [comment]
I see that you did not create a fork of ShellAnything. Would you like to contribute to the project? If so, please so in the comments and I will assign you this issue.

**Comment by Cirn09** [comment]
I have no experience in large C++ projects, dont know how to contribute this project, so I’m not going to create a fork.

**Comment by end2endzone** [comment]
**Regarding the maximum length of a menu name...**

I did more testing with the maximum length of a menu. The documentation about menus functions (such as 
[GetMenuString()](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmenustringw), [GetMenuItemInfoW()](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmenuiteminfow), [InsertMenuItemW()](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-insertmenuitemw) and [AppendMenuW()](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-appendmenuw) ) do not list a maximum length.

Using a try and errors, I found out that maximum length of a menu (at least on Windows 7) is 259 characters. Over this limit, Windows will truncate the string. For testing, I created a new Win32 project (a native win32 GUI app) to which I added a popup menu with samples entries.
The last menu entry was added with the following:
```cpp
std::string tmp;
tmp.append(258, ' ');
tmp.append(1, 'z');
AppendMenuA(hPopupMenu, MF_STRING, IDM_EXIT, tmp.c_str());
```

With a string of 259 characters, the last character `z` was still displayed but when I added 259 spaces followed by the `z` character, making the string 260 characters, the last character was truncated (I did not see the `z` character).

I suggest setting the default maximum length to 250 characters.
If a menu name is longer than `max_length` characters, ShellAnything shall truncate the string to a maximum of `max_length` character.
If `max_length` is set to the default value of 250 characters, ShellAnything shall also add "..." as an indicator that the name was truncated.




**Regarding special character that would need escaping...**

I found that there are only 3 specials characters:
* Ampersand (`&`) is used for mnemonics. These are the underlined characters in each menu item that are used to navigate menus using keyboard shortcuts, a.k.a. Menu Access Keys. See the documentation about [Menu Access Keys](https://docs.microsoft.com/en-us/windows/win32/menurc/about-menus#menu-access-keys) for details.
* The `\t` character is used to create a column/space in the menu. This feature is used for accelerators. For instance, the "File\Open" menu is defined as `Open\tCtrl+O` where "Ctrl+O" is displayed on the side of a menu as an accelerator to open a file. The `\t` character is used for alignment only, it does not register the accelerator on the system. In other words, Ctrl+O is only text and won't actially execute the menu. See the documentation about [Menu Shortcut Keys](https://docs.microsoft.com/en-us/windows/win32/menurc/about-menus#menu-shortcut-keys) for details.
* The `\a` character is used to aligns all text that follows it flush right to the menu bar or pop-up menu according to the [MENUITEM](https://docs.microsoft.com/en-us/windows/win32/menurc/menuitem-statement) documentation. However, it does not seems to be working on Windows 7.

I do not wish to automatically escape the ampersand character to a double-ampersand. The mnemonics feature is already known to Windows users. It also allow one to create menu entries such as:
```xml
<menu name="Press the &amp;z key to execute this menu" >
  <actions>
    <message title="It works!" />
  </actions>
</menu>
```

The `\t` character does not require escaping and should be interpreted as usual and produce the expected result. If one want to have spaced instead of tabs in a menu name then it should change the content of the configuration or the values of the properties.

For testing the `\a` character, I created a menu item with `AppendMenuA(hPopupMenu, MF_STRING, IDM_EXIT, "Play1\aPlay2");` but the character is not recognized as a control character but is rendered as an "unknown" character:  ![image](https://user-images.githubusercontent.com/31753093/88606219-1bc0d100-d04a-11ea-86e7-9f69a41cdacf.png)


To prevent issues with users not understanding why the string "Smith&Co" is actually rendered as "SmithCo", I will add a section in the document about mnemonics.

For other characters, the following was found:
* Ascii code 1 to 31 cannot be displayed (with some exceptions).
* Ascii code 32 to 127 (except ampersand character) do not need escaping.
* Ascii code 128 to 255 are system specific characters. On my system which uses Windows CP 1252, **most** characters are rendered properly and do not require escaping. Exceptions are 0x8d, 0x8f, 0x90 and 0x9d. I did not investigate these characters.

Using the following code, I create a menu item example of all characters:
```cpp
for(int i = 1; i <= 255; i++)
{
  static const int BUFFER_SIZE = 1024;
  char buffer[BUFFER_SIZE];
  sprintf_s(buffer, "%d 0x%02X a%ca", i, i, (char)i);

  UINT uFlags = MF_STRING;
  if (i > 0 && i%40 == 0)
    uFlags = uFlags | MF_MENUBREAK;

  AppendMenuA(hPopupMenu, uFlags, IDM_EXIT, buffer);
}
```
which rendered the following menu items:
![image](https://user-images.githubusercontent.com/31753093/88606243-2da27400-d04a-11ea-8a23-4016d1f4ac54.png)



Also, for implementing the `max_length` attribute, I will probably need a truncate string function that can userstand utf-8 characters codes in order to prevent truncating "in the middle" of a multibyte character. Any good reference ?

**Comment by end2endzone** [comment]
Hi. I recently pushed new changes about this issue in branch `feature-issue55`. Please take a look at the changes and tell me what you think. Feel free to make corrections and push the changes to my branch as kind of a peer review.

In summary:
* I created unicode.h with functions for implementing substring with utf-8 encoded strings.
* I implemented Menu::TruncateName(), Menu::GetNameMaxLength() and SetNameMaxLength() to handle the maximum length of a name. The menu descriptions are also truncated to the maximum length. The default value for `GetNameMaxLength()` is 250 as previously discussed.
* I used the name `maxlength` instead of `max_length` as the attribute for the `<menu>` element. This name was more in lined with the other attribute names such as `fileextensions`, `fileextension`, `basedir`, `maxfiles`, `maxfolders` and others.
* I updated the documentation. See the following new sections: [maxlength attribute](https://github.com/end2endzone/ShellAnything/blob/feature-issue55/UserManual.md#maxlength-attribute), [Keyboard mnemonics](https://github.com/end2endzone/ShellAnything/blob/feature-issue55/UserManual.md#mnemonics--keyboard-shortcuts) and [this new section](https://github.com/end2endzone/ShellAnything/blob/feature-issue55/UserManual.md#missing-ampersand-character--in-menus) in the Troubleshooting section.

P.S. I have not tried the changes on a "live" system yet.

**Comment by Cirn09** [comment]
I am not familiar with C++ language. So it is enough for me that if it works well.

**Comment by end2endzone** [comment]
The issue is now integrated into master branch.
