### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by robert-boulanger** [end2endzone/ShellAnything#67]
Node.cpp(68,18): error C2039: "runtime_error" is not a  member of "std".

Solution:
`#include <stdexcept> `

in Node.cpp

**Comment by end2endzone** [comment]
Hi.
Thank you for the feedback. I appreciate it.

You are right, the include for `std::runtime_error` is missing.

However, I develop on Visual Studio 2010 and appveyor is building on Visual Studio 2015. Both do not complain about the missing include (which is why I did not catch this issue). The missing include is probably already included by another include in Node.cpp.

May I ask you a question about you development environment? I would like to know which platform or compiler are you using? Are you using Visual Studio Code or Mingw?

Most of the time, I get these kind of issues when building on Linux. The "official" include for a function is missing but Visual Studio somehow is including everything that is required through another included file.

**Comment by robert-boulanger** [comment]
Hi,

there was a visual studio code installed on the machine where I tried to build it, but I never use it.
Normally I have Mingw here and this is only used to compile python code via nuitka to native executables.
I just followed your build instructions, installed cmake and all the other dependencies. 
However it's about 30 years I touched C the last time in a productive manner, whatever happened in meantime in the c world happened without me ;)

But I think its using the MSVC compiler, as you can see here:
 
```

-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
-- The C compiler identification is MSVC 19.26.28806.0
-- The CXX compiler identification is MSVC 19.26.28806.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done

```
Also this issue was fixed, I'm getting the next troubles.
As mentioned above, when following the build instructions, building shellanywhere now complains that it does not find tinyxml2_static.lib, and indeed there is only a tinyxml2.lib present. But maybe this has to do with this: https://github.com/leethomason/tinyxml2/issues/588 and not with your build instructions of shellanywhere.

However, I just detected the shellanywhere project and wanted to test an idea for an application mockup/prototype and since there is no compiled binary available I had to jump in that cold water and tried to build it by myself, but as I told, I'm not from the windows c planet, so I feel a bit like an alien from outerspace here ;)

**Comment by end2endzone** [comment]
Hi.

Looking at your log sample, you seem to be using Visual Studio 2019 which I never tested. Maybe this was the reason for the missing include. Anyway, the issue is now fixed.

> and since there is no compiled binary available...

The [INSTALL.md documentation](https://github.com/end2endzone/ShellAnything/blame/eadf63b40efc8e6dc21a48e80951af6d7ce3a5c7/INSTALL.md#L3) says that '_application does not provides pre-build binaries_' which is incorrect. I created #68 to resolve this. Thanks for pointing that out. I am sorry. I hope that this poor documentation does not makes the ShellAnything experience too disappointing.

For your information, you can find compiled binaries in the [project release page](https://github.com/end2endzone/ShellAnything/releases). The official latest release is version 0.4.0. You can also checkout the [latest/nightly builds](https://ci.appveyor.com/project/end2endzone/shellanything) available on the appveyor which offers CI/CD service for Windows. If you see a vertical green line, it means the build was a success. Select the `Platform: x64`, then look in the `Artifacts` tab. For example, https://ci.appveyor.com/project/end2endzone/shellanything/build/job/9b8ovvjj8jdosnwe/artifacts. You will find 2 installers, one is a traditional "setup.exe" and the other is a more modern MSI. A portable version is also available. I recommend to use the setup.exe version because the MSI installer is less than 1 week old.

> But maybe this has to do with this: leethomason/tinyxml2 #588 and not with your build instructions of shellanywhere

I think you are right. Looking at the file [src/CMakeLists.txt, line 149](https://github.com/end2endzone/ShellAnything/blob/eadf63b40efc8e6dc21a48e80951af6d7ce3a5c7/src/CMakeLists.txt#L149), I think I have hardcoded the use of tinyxml2 static library (tinyxml2_static.lib). My appveyor's installation script [install_tinyxml2.bat](https://github.com/end2endzone/ShellAnything/blob/eadf63b40efc8e6dc21a48e80951af6d7ce3a5c7/ci/appveyor/install_tinyxml2.bat#L30) is also forcing to build tinyxml2 as a static library. Shame on me. I tend to forget that people may install dependencies in a different configuration than me.

I will try the proposed solution (below) and will let you know:
```
if (TARGET tinyxml2)
target_link_libraries(my_lib PRIVATE tinyxml2)
else()
target_link_libraries(my_lib PRIVATE tinyxml2_static)
endif()
```

As a side note, you can take a look at the build scripts used on appveyor. These scripts extract and build all dependencies under the `build` directory and sub directories. The binaries are not install "somewhere" on the system but **only** under the build directory. These might gave you hints on what is expected by ShellAnything CMake scripts.

**Comment by end2endzone** [comment]
I made the corrections that should allow you to compile ShellAnything with support for both tinyxml2 configurations. See the build log at https://ci.appveyor.com/project/end2endzone/shellanything/build/job/ad1angjey75ddxgy. The build on appveyor was not modified and still uses a static library.

However, for testing, I changed [install_tinyxml2.bat, line 30](https://github.com/end2endzone/ShellAnything/blob/eadf63b40efc8e6dc21a48e80951af6d7ce3a5c7/ci/appveyor/install_tinyxml2.bat#L30) to `-DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=OFF`. This made my local copy of tinyxml2 build as a shared library.

The proposed changes specified in the previous comment was implemented in fcf3f9687733cdd1a3ca9f1e26b115036b2cb68d and I was able to compile with a shared library. If you also compiled the other dependencies (gtest, glog, rapidassist and win32clipboard) as static libraries, you should not run into issues.

Note that when building tinyxml2 as a shared library, the dll (`tinyxml2d.dll` in debug, `tinyxml2.dll` in release) is not copied in the output binary directory of ShellAnything. If you try to run/install ShellAnything or execute unit tests, you may run into the following error message:
```
---------------------------
shellanything_unittest-d.exe - System Error
---------------------------
The program can't start because tinyxml2d.dll is missing from your computer. Try reinstalling the program to fix this problem. 
---------------------------
OK   
---------------------------
```

To solve this issue, you may do one of the following:
- Copy tinyxml2.dll manually into ShellAnything's output directory.
- Add the directory that contains `tinyxml2.dll` in your PATH environment variable.

I was expecting CMake to understand that tinyxml2 is a shared library and should be automatically packaged with the package installers or with the INSTALL target. I guess CMake is expecting users to use the `PATH` environment variable.
It is one of the reasons why I prefer to use static libraries (even of the binary output is bigger and that I won't get automatic tinyxml2 security updates and other stuff).

I also created #70 so that Win32Clipboard library would be merged into ShellAnything source code reducing the number of required dependencies by 1 but more importantly, getting rid of any issues about building Win32Clipboard in static or shared mode.

As I final note, I hope that you still have the will to keep going and try to build ShellAnything yourself. The feedback you are giving me is gold and I will do my best to provide support. I am also happy to make ShellAnything more available to others (and easier to build). Looking forward for your feedback.

**Comment by robert-boulanger** [comment]
Thanks so far, will have a look on this after my holidays.
So long...

**Comment by end2endzone** [comment]
Did you had time to look at the changes? Does it solves you issue? Also, the last issue related to [milestone 0.5.0](https://github.com/end2endzone/ShellAnything/milestone/2) will be resolved in a few days. You might want to have a look at the latest version.

**Comment by robert-boulanger** [comment]
Seems to work now.
